### ISSUE TITLE
give a example to send logs to cloudwatch 

### ISSUE THREAD

**Issue by rafilkmp3** [cn-terraform/terraform-aws-ecs-fargate-service#10]
could please include a example to send logs to `awslogs`  ?

**Comment by jnonino** [comment]
Hi, here you can find an example I did using the other modules including the CloudWatch service.

https://github.com/jnonino/symmetrical-spork/tree/master/terraform/aws

**Comment by rafilkmp3** [comment]
thanks @jnonino  you are amazing
