### ISSUE TITLE
Security group ingress/egress rule overwrite

### ISSUE THREAD

**Issue by sps-software** [cn-terraform/terraform-aws-ecs-fargate-service#12]
Hi,

Upon trying to use the module, I get this error: 

```
Error: [WARN] A duplicate Security Group rule was found on (sg-06b5d95a1643cbaa9). This may be
a side effect of a now-fixed Terraform issue causing two security groups with
identical attributes but different source_security_group_ids to overwrite each
other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
information and instructions for recovery. Error message: the specified rule "peer: sg-0acd84d530dea5135, TCP, from port: 443, to port: 443, ALLOW" already exists
```

I believe it may be linked to this commit:
923354cdce725ce615b21d4422dfcedaec27bdc1

and may have to do with this clause in the Terraform security group resource docs:

"NOTE on Security Groups and Security Group Rules: Terraform currently provides both a standalone Security Group Rule resource (a single ingress or egress rule), and a Security Group resource with ingress and egress rules defined in-line. At this time you cannot use a Security Group with in-line rules in conjunction with any Security Group Rule resources. Doing so will cause a conflict of rule settings and will overwrite rules."

which can be found here: https://www.terraform.io/docs/providers/aws/r/security_group.html

I think the 0.0.0.0/0 egress needs to be moved to its own rule as well, in order to fit within this structure. I can test it out and let you know/put in a PR if I have permission.

Best,
Steven

**Comment by sps-software** [comment]
Whoops, looks like this is probably on my side. Apologies.

**Comment by jnonino** [comment]
Hi, no problem, please let me know about any issues.
