### ISSUE TITLE
ECS service with an NLB

### ISSUE THREAD

**Issue by roded** [cn-terraform/terraform-aws-ecs-fargate-service#53]
Hello,
Is it possible to use this module to create an ECS service with an NLB instead of an ALB?
Alternatively, is it possible to supplier an external LB arn to attach to the service?
Thanks

Edit: Similarly, it would be useful to be able to provision a service with no defined LB.

**Comment by jnonino** [comment]
Hi, version 2.0.32 have a variable to provide a custom LB instead of creating the LB in the module. Please reopen if that is not enough for your use case or if there are any issues.
Thanks!
