### ISSUE TITLE
Option for enabling deployment_circuit_breaker

### ISSUE THREAD

**Issue by akaiypova-jetty** [cn-terraform/terraform-aws-ecs-fargate-service#59]
Can you please add an option for enabling deployment_circuit_breaker? This isn't enabled by default.
```
resource "aws_ecs_service" "mongo" {
  name            = "my_ecs"

  deployment_circuit_breaker {
    enable  = true
    rollback = ture
  }
}
```

**Comment by akaiypova-jetty** [comment]
hi @jnonino! Is there a way to move this issue up? Can I submit a PR with a fix? Thank you.

**Comment by jnonino** [comment]
Hi @akaiypova-jetty, sure!! You can submit a PR for this!!

**Comment by akaiypova-jetty** [comment]
@jnonino When you get a chance, please review my PR https://github.com/cn-terraform/terraform-aws-ecs-fargate-service/pull/61. Thank you!

**Comment by jnonino** [comment]
Hi, I checked the PR.

Pipeline is failing with this error:

```
Run terraform validate
╷
│ Error: Unsupported argument
│ 
│   on ../../main.tf line 72, in resource "aws_ecs_service" "service":
│   72:   deployment_circuit_breaker         = var.deployment_circuit_breaker
│ 
│ An argument named "deployment_circuit_breaker" is not expected here. Did
│ you mean to define a block of type "deployment_circuit_breaker"?
╵
Error: Process completed with exit code 1.
```

**Comment by akaiypova-jetty** [comment]
hi @jnonino! Sorry for the delayed response. I just updated the PR, please review it again. Thank you!
