### ISSUE TITLE
Unused KMs key

### ISSUE THREAD

**Issue by joeyrogues** [cn-terraform/terraform-aws-ecs-fargate-service#6]
I might be mistaken but I think the following key is not used, thus created for nothing

`main.tf`
```hcl
resource "aws_kms_key" "encryption_key" {
  description         = "${var.name_preffix} ECS Encryption Key"
  is_enabled          = true
  enable_key_rotation = true
}
```

**Comment by jnonino** [comment]
Hi, thank you, fixed on [1.0.8](https://registry.terraform.io/modules/cn-terraform/ecs-fargate-service/aws/1.0.8)
